// ============================================================================
// COPIED FROM ../remus_dotnet/src/Remus.Web/Data/ - DO NOT EDIT IN ISOLATION.
//
// This project SHARES the `remus_dotnet` PostgreSQL database with the Blazor
// app. That app owns the schema and the migration history; this one only reads
// and writes. There is deliberately no Data/Migrations folder here and nothing
// ever calls Database.Migrate().
//
// Consequence: this file must stay byte-for-byte equivalent (namespace aside)
// to its twin. If EF's model drifts from the real tables, queries fail at
// runtime with "column does not exist" rather than at build time.
//
// Django analogue: two Django projects pointed at one database, where only one
// has the migrations and the other runs with `managed = False` models.
// ============================================================================

namespace Remus.Mvc.Data;

/// <summary>
/// Biographical data for a user. One profile per user, always.
/// </summary>
/// <remarks>
/// Django equivalent (users/models.py in remus_local):
///
///     class Profile(models.Model):
///         user = models.OneToOneField(
///             settings.AUTH_USER_MODEL,
///             on_delete=models.CASCADE,
///             related_name="profile",
///         )
///         ...
///
/// A few structural differences from a Django model class:
///
/// * This is a plain C# class ("POCO"). It does not inherit from anything, has
///   no metaclass, no `objects` manager, and no knowledge that a database
///   exists. Django models are active-record-ish: `profile.save()` writes a row.
///   EF Core entities are passive: the DbContext tracks them and writes on
///   SaveChangesAsync. So there is no Profile.objects.filter(...) here - queries
///   live on the context (db.Profiles.Where(...)), which is why ProfileService
///   exists at all.
///
/// * There is no inner `class Meta`. Table name, indexes, max lengths and the
///   relationship are all configured in Data/Configurations/ProfileConfiguration.cs.
///   EF calls that the "fluent API"; it is the recommended home for mapping so
///   the entity stays free of persistence concerns.
///
/// * Nullability is expressed by the C# type, not a kwarg. `string?` means the
///   column is nullable; `string` (no ?) means NOT NULL. Django splits this into
///   null= (database) and blank= (forms) on one field; .NET splits it across two
///   different mechanisms - the type for the database, [Required] on the *form*
///   model for validation. See Models/ProfileFormModel.cs.
/// </remarks>
public class Profile : IAuditedEntity
{
    // Django gives every model an implicit `id` (BigAutoField since 3.2, so
    // bigint). We declare it explicitly; EF's convention is that a property
    // named Id or <Type>Id is the primary key, and an int PK is generated by
    // the database. Using int rather than long here purely for simplicity -
    // remus_local's users_profile.id is bigint.
    public int Id { get; set; }

    // ---- the one-to-one link -------------------------------------------------
    // Django: user = models.OneToOneField(AUTH_USER_MODEL, on_delete=CASCADE,
    //                                     related_name="profile")
    //
    // In EF that single line becomes three things:
    //   1. UserId  - the foreign key column (string, because IdentityUser.Id is
    //                a string GUID; remus_local uses bigint because Django's
    //                CustomUser has an integer pk).
    //   2. User    - the navigation property, i.e. the object on the other end.
    //   3. the mapping in ProfileConfiguration, which is what actually makes it
    //      ONE-to-one rather than many-to-one, by putting a unique index on
    //      UserId. Exactly what users_profile_user_id_key does in remus_local.
    //
    // `= null!` tells the compiler "trust me, EF will populate this" so that
    // non-nullable reference types do not produce a warning on a property the
    // constructor cannot set. It is a promise to the compiler, not to the
    // runtime: if you forget .Include(p => p.User), User really is null.
    // Django would have lazily fetched it. EF will not.
    public string UserId { get; set; } = null!;
    public ApplicationUser User { get; set; } = null!;

    // ---- identity / naming ---------------------------------------------------
    public Title? Title { get; set; }
    public Gender? Gender { get; set; }

    // remus_local keeps first_name/last_name on BOTH customuser and profile.
    // We keep them only here: AspNetUsers has no name columns at all, which is
    // the cleaner split (AspNetUsers = credentials, Profile = who you are).
    public string? FirstName { get; set; }
    public string? LastName { get; set; }

    // ---- birth ---------------------------------------------------------------
    // DateOnly (C# 10+) maps to Postgres `date`, matching users_profile.date_birth.
    // Using DateTime here would silently give you `timestamp` and a midnight
    // component you never wanted - a common first-migration mistake.
    public DateOnly? DateBirth { get; set; }
    public string? PlaceBirth { get; set; }

    // ---- location ------------------------------------------------------------
    public string? City { get; set; }

    // ISO 3166-1 alpha-2, char(2), same as remus_local. Kept as a string rather
    // than an enum: there are ~250 of them and they change.
    public string? Country { get; set; }
    public string? Nationality { get; set; }

    // ---- professional --------------------------------------------------------
    public string? Position { get; set; }
    public string? Institution { get; set; }

    // Django: models.TextField(null=True) -> Postgres `text`.
    // EF maps string to `text` by default on Npgsql, so "unbounded" is the
    // default and it is the *max length* that needs configuring, the opposite
    // of Django's CharField/TextField split.
    public string? Biography { get; set; }

    // ---- avatar --------------------------------------------------------------
    // Django: models.ImageField(upload_to="profiles/") - stores a relative path
    // string in the column and handles the file via MEDIA_ROOT/MEDIA_URL plus a
    // storage backend.
    //
    // .NET has no FileField. This is just a string holding a path; writing the
    // bytes somewhere is our job (Services/LocalAvatarStorage.cs). That is less
    // convenient than Django and more explicit about what is actually happening.
    public string? ProfileImage { get; set; }

    // ---- workflow ------------------------------------------------------------
    // Non-nullable with a default, unlike remus_local where is_validated is
    // nullable. A nullable bool in C# is bool? and has three states, which is
    // almost never what you want.
    public bool IsValidated { get; set; }

    // ---- audit (see IAuditedEntity) -----------------------------------------
    // DateTimeOffset maps to `timestamp with time zone`, matching Django's
    // USE_TZ=True DateTimeField. Prefer it over DateTime, which maps to
    // `timestamp without time zone` and loses the offset.
    public DateTimeOffset Created { get; set; }
    public DateTimeOffset LastUpdate { get; set; }

    // ---- convenience ---------------------------------------------------------
    // Django: a @property on the model, or a method decorated with @property.
    // Same idea; EF ignores read-only computed properties automatically because
    // they have no setter, so no [NotMapped] attribute is needed here.
    public string FullName =>
        string.Join(" ", new[] { FirstName, LastName }.Where(s => !string.IsNullOrWhiteSpace(s)));

    /// <summary>Name to show in the UI, never empty.</summary>
    public string DisplayName =>
        !string.IsNullOrWhiteSpace(FullName) ? FullName : User?.Email ?? "Unnamed user";
}
